name = "vibecli-web"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "out"

[env.production]
name = "vibecli-web-production"

[env.preview]
name = "vibecli-web-preview"

# Environment Variables
[vars]
NEXT_PUBLIC_APP_URL = "https://vibecli.150404.xyz"

# Custom domain configuration (for reference)
# Domain: vibecli.150404.xyz should be added via Cloudflare Dashboard